spring:
  application:
    name: resilience4j-reactive-demo

resilience4j.circuitbreaker:
  configs:
    default:
      minimumNumberOfCalls: 10
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      waitDurationInOpenState: 100ms
      failureRateThreshold: 30
      eventConsumerBufferSize: 2
      registerHealthIndicator: true
    instances:
      orderVendorAPICB:
        name: orderVendorAPICB
        baseConfig: default

management:
  endpoints:
    web:
      exposure:
        include: '*'