spring:
  application:

#TODO - This is not loading in tests
resilience4j.circuitbreaker:
  configs:
    default:
      minimumNumberOfCalls: 10
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      waitDurationInOpenState: 100ms
      failureRateThreshold: 30
      eventConsumerBufferSize: 2
      registerHealthIndicator: true
    instances:
      unstableService:
        name: unstableService
        baseConfig: default
management:
  endpoints:
    web:
      exposure:
        include: '*'